ALTER DEFAULT PRIVILEGES
FOR USER gugik2osm
IN SCHEMA public
GRANT SELECT ON TABLES TO public;

ALTER DEFAULT PRIVILEGES
FOR USER gugik2osm
IN SCHEMA changesets_processing
GRANT SELECT ON TABLES TO public;

ALTER DEFAULT PRIVILEGES
FOR USER gugik2osm
IN SCHEMA bdot
GRANT SELECT ON TABLES TO public;

ALTER DEFAULT PRIVILEGES
FOR USER gugik2osm
IN SCHEMA prg
GRANT SELECT ON TABLES TO public;

ALTER DEFAULT PRIVILEGES
FOR USER gugik2osm
IN SCHEMA teryt
GRANT SELECT ON TABLES TO public;
