insert into process_locks values
('prg_full_update', false, null, null, null, 'Cotygodniowa aktualizacja danych PRG'),
('prg_partial_update', false, null, null, null, 'Cominutowa aktualizacja danych OSM'),
('teryt_update', false, null, null, null, 'Codzienna aktualizacja danych TERYT'),
('db_lock', false, null, null, null, 'Blokada dostępu do bazy danych (przerwa techniczna)')
on conflict do nothing
;

-- m column is going to be either text mapping or empty string for further ease of processing
insert into teryt.cecha_mapping values
('ul.', ''),
('al.', 'Aleja'),
('pl.', 'Plac'),
('skwer', 'Skwer'),
('bulw.', 'Bulwar'),
('rondo', 'Rondo'),
('park', 'Park'),
('rynek', 'Rynek'),
('szosa', ''),
('droga', ''),
('os.', 'Osiedle'),
('wyspa', 'Wyspa'),
('wyb.', 'Wybrzeże'),
('inne', '')
on conflict do nothing
;


INSERT INTO bdot.lookup_funogolnabudynku VALUES
('1110', 'budynki mieszkalne jednorodzinne'),
('1121', 'budynki o dwóch mieszkaniach'),
('1122', 'budynki o trzech i więcej mieszkaniach'),
('1130', 'budynki zbiorowego zamieszkania'),
('1211', 'budynki hoteli'),
('1212', 'pozostałe budynki zakwaterowania turystycznego'),
('1220', 'budynki biurowe'),
('1230', 'budynki handlowo-usługowe'),
('1241', 'budynki łączności dworców i terminali'),
('1242', 'garaże'),
('1251', 'budynki przemysłowe'),
('1252', 'zbiorniki, silosy lub budynki magazynowe'),
('1261', 'ogólnodostępne budynki kulturalne'),
('1262', 'muzea lub biblioteki'),
('1263', 'budynki szkół i instytucji badawczych'),
('1264', 'budynki szpitali i zakładów opieki medyczne'),
('1265', 'budynki kultury fizycznej'),
('1271', 'budynki gospodarstwa rolnego'),
('1272', 'budynki kultu religijnego'),
('1273', 'budynek zabytkowy'),
('1274', 'pozostałe budynki niemieszkalne')
on conflict do nothing
;

INSERT INTO bdot.lookup_funszczegolowabudynku VALUES
('1110.Dj', 'budynek jednorodzinny'),
('1110.Dl', 'dom letniskowy'),
('1110.Ls', 'leśniczówka'),
('1121.Db', 'budynek o dwóch mieszkaniach'),
('1122.Dw', 'budynek wielorodzinny'),
('1130.Bs', 'bursa szkolna'),
('1130.Db', 'dom dla bezdomnych'),
('1130.Dd', 'dom dziecka'),
('1130.Os', 'dom opieki społecznej'),
('1130.Dp', 'dom parafialny'),
('1130.Ds', 'dom studencki'),
('1130.Dz', 'dom zakonny'),
('1130.Hr', 'hotel robotniczy'),
('1130.In', 'internat'),
('1130.Kl', 'klasztor'),
('1130.Km', 'koszary'),
('1130.Po', 'placówka opiekuńczo-wychowawcza'),
('1130.Ra', 'rezydencja ambasadora'),
('1130.Rb', 'rezydencja biskupia'),
('1130.Rp', 'rezydencja prezydencka'),
('1130.Zk', 'zakład karny'),
('1130.Zp', 'zakład poprawczy'),
('1211.Dw', 'dom weselny'),
('1211.Ht', 'hotel'),
('1211.Mt', 'motel'),
('1211.Pj', 'pensjonat'),
('1211.Rj', 'restauracja'),
('1211.Zj', 'zajazd'),
('1212.Dk', 'domek kempingowy'),
('1212.Dr', 'dom rekolekcyjny'),
('1212.Dw', 'dom wypoczynkowy'),
('1212.Os', 'ośrodek szkoleniowo wypoczynkowy'),
('1212.St', 'schronisko turystyczne'),
('1220.Bk', 'bank'),
('1220.Ck', 'centrum konferencyjne'),
('1220.Km', 'Kuria Metropolitarna'),
('1220.Mn', 'ministerstwo'),
('1220.Pd', 'placówka dyplomatyczna lub konsularna'),
('1220.Pc', 'policja'),
('1220.Pk', 'prokuratura'),
('1220.Pg', 'przejście graniczne'),
('1220.Sd', 'sąd'),
('1220.Sf', 'siedziba firmy lub firm'),
('1220.Pw', 'Starostwo Powiatowe'),
('1220.Sg', 'straż graniczna'),
('1220.Sp', 'straż pożarna'),
('1220.Uc', 'Urząd Celny'),
('1220.Ug', 'Urząd Gminy'),
('1220.Um', 'Urząd Miasta'),
('1220.Umg', 'Urząd Miasta i Gminy'),
('1220.Mr', 'Urząd Marszałkowski'),
('1220.Up', 'placówka operatora pocztowego'),
('1220.Uw', 'Urząd Wojewódzki'),
('1220.Ap', 'inny urząd administracji publicznej'),
('1230.Ap', 'apteka'),
('1230.Ch', 'centrum handlowe'),
('1230.Dh', 'dom towarowy lub handlowy'),
('1230.Ht', 'hala targowa'),
('1230.Hw', 'hala wystawowa'),
('1230.Hm', 'hipermarket lub supermarket'),
('1230.Ph', 'pawilon handlowo-usługowy'),
('1230.So', 'stacja obsługi pojazdów'),
('1230.Sp', 'stacja paliw'),
('1241.Kk', 'budynek kontroli ruchu kolejowego'),
('1241.Kp', 'budynek kontroli ruchu powietrznego'),
('1241.Ct', 'centrum telekomunikacyjne'),
('1241.Da', 'dworzec autobusowy'),
('1241.Dk', 'dworzec kolejowy'),
('1241.Dl', 'dworzec lotniczy'),
('1241.Hg', 'hangar'),
('1241.Lm', 'latarnia morska'),
('1241.Lk', 'lokomotywownia lub wagonownia'),
('1241.Kg', 'stacja kolejki górskiej lub wyciągu krzesełkowego'),
('1241.Rt', 'stacja nadawcza radia i telewizji'),
('1241.Tp', 'terminal portowy'),
('1241.Ab', 'zajezdnia autobusowa'),
('1241.Tr', 'zajezdnia tramwajowa'),
('1241.Tb', 'zajezdnia trolejbusowa'),
('1242.Gr', 'garaż'),
('1242.Pw', 'parking wielopoziomowy'),
('1251.El', 'elektrociepłownia'),
('1251.Ek', 'elektrownia'),
('1251.Kt', 'kotłownia'),
('1251.Mn', 'młyn'),
('1251.Pr', 'produkcyjny'),
('1251.Rf', 'rafineria'),
('1251.Ss', 'spalarnia śmieci'),
('1251.Wr', 'warsztat remontowo-naprawczy'),
('1251.Wt', 'wiatrak'),
('1252.Sp', 'budynek spedycji'),
('1252.Ch', 'chłodnia'),
('1252.El', 'elewator'),
('1252.Mg', 'magazyn'),
('1252.Sl', 'silos'),
('1252.Gz', 'zbiornik na gaz'),
('1252.Ci', 'zbiornik na ciecz'),
('1261.Oz', 'budynek ogrodu zoo lub botanicznego'),
('1261.Dk', 'dom kultury'),
('1261.Fh', 'filharmonia'),
('1261.Hw', 'hala widowiskowa'),
('1261.Ks', 'kasyno'),
('1261.Kn', 'kino'),
('1261.Kl', 'klub, dyskoteka'),
('1261.Op', 'opera'),
('1261.Sz', 'schronisko dla zwierząt'),
('1261.Tt', 'teatr'),
('1262.Ar', 'archiwum'),
('1262.Bl', 'biblioteka'),
('1262.Ci', 'centrum informacyjne'),
('1262.Gs', 'galeria sztuki'),
('1262.Mz', 'muzeum'),
('1263.Ob', 'obserwatorium lub planetarium'),
('1263.Pb', 'placówka badawcza'),
('1263.Ps', 'przedszkole'),
('1263.Sh', 'stacja hydrologiczna'),
('1263.Sm', 'stacja meteorologiczna'),
('1263.Sp', 'szkoła podstawowa'),
('1263.Sd', 'szkoła ponadpodstawowa'),
('1263.Sw', 'szkoła wyższa'),
('1264.Hs', 'hospicjum'),
('1264.Iw', 'izba wytrzeźwień'),
('1264.Jr', 'jednostka ratownictwa medycznego'),
('1264.Kw', 'klinika weterynaryjna'),
('1264.Oo', 'ośrodek opieki społecznej'),
('1264.Po', 'placówka ochrony zdrowia'),
('1264.St', 'sanatorium'),
('1264.Sk', 'stacja krwiodawstwa'),
('1264.Ss', 'stacja sanitarno-epidemiologiczna'),
('1264.Sz', 'szpital'),
('1264.Zb', 'żłobek'),
('1265.Hs', 'hala sportowa'),
('1265.Ht', 'halowy tor gokartowy'),
('1265.Ks', 'klub sportowy'),
('1265.Kt', 'korty tenisowe'),
('1265.Kr', 'kręgielnia'),
('1265.Pl', 'pływalnia'),
('1265.Sg', 'sala gimnastyczna'),
('1265.St', 'strzelnica'),
('1265.Sl', 'sztuczne lodowisko'),
('1265.Uj', 'ujeżdżalnia'),
('1271.Bg', 'budynek gospodarczy'),
('1271.Bp', 'budynek produkcyjny zwierząt hodowlanych'),
('1271.St', 'stajnia'),
('1271.Sz', 'szklarnia lub cieplarnia'),
('1272.Bc', 'budynki cmentarne'),
('1272.Ck', 'cerkiew'),
('1272.Dp', 'dom pogrzebowy'),
('1272.Dz', 'dzwonnica'),
('1272.Ir', 'inny budynek kultu religijnego'),
('1272.Kp', 'kaplica'),
('1272.Ks', 'kościół'),
('1272.Kr', 'krematorium'),
('1272.Mc', 'meczet'),
('1272.Sn', 'synagoga'),
('1273.Zb', 'zabytek bez funkcji użytkowej'),
('1274.As', 'areszt śledczy'),
('1274.Bc', 'bacówka'),
('1274.Sc', 'schronisko dla nieletnich'),
('1274.Sg', 'stacja gazowa'),
('1274.Sp', 'stacja pomp'),
('1274.St', 'stacja transformatorowa'),
('1274.Tp', 'toaleta publiczna'),
('1274.Zk', 'zabudowania koszarowe'),
('1274.Zp', 'zakład karny lub poprawczy')
on conflict do nothing
;

INSERT INTO bdot.lookup_x_katistnienia VALUES
('Eks', 'eksploatowany'),
('Bud', 'w budowie'),
('Zns', 'zniszczony'),
('Tmc', 'tymczasowy'),
('Ncn', 'nieczynny')
on conflict do nothing
;

INSERT INTO bdot.lookup_x_kod VALUES
('BUBD01', 'budynki mieszkalne jednorodzinne'),
('BUBD02', 'budynki o dwóch mieszkaniach'),
('BUBD03', 'budynki o trzech i więcej mieszkaniach'),
('BUBD04', 'budynki zbiorowego zamieszkania'),
('BUBD05', 'budynki hoteli'),
('BUBD06', 'budynki zakwaterowania turystycznego, pozostałe'),
('BUBD07', 'budynki biurowe'),
('BUBD08', 'budynki handlowo-usługowe'),
('BUBD09', 'budynki łączności, dworców i terminali'),
('BUBD10', 'budynki garaży'),
('BUBD11', 'budynki przemysłowe'),
('BUBD12', 'zbiorniki, silosy i budynki magazynowe'),
('BUBD13', 'ogólnodostępne obiekty kulturalne'),
('BUBD14', 'budynki muzeów i bibliotek'),
('BUBD15', 'budynki szkół i instytucji badawczych'),
('BUBD16', 'budynki szpitali i zakładów opieki medycznej'),
('BUBD17', 'budynki kultury fizycznej'),
('BUBD18', 'budynki gospodarstw rolnych'),
('BUBD19', 'budynki przeznaczone do sprawowania kultu religijnego i czynności religijnych'),
('BUBD20', 'obiekty budowlane wpisane do rejestru zabytków i objęte indywidualną ochroną konserwatorską oraz nieruchome, archeologiczne dobra kultury'),
('BUBD21', 'pozostałe budynki niemieszkalne, gdzie indziej nie wymienione')
on conflict do nothing
;
