create table if not exists street_names_mappings (
  original_name text primary key,
  osm_name text not null
);

-- source: https://wiki.openstreetmap.org/wiki/User:Gsapijaszko/punktyadresowe_import
insert into street_names_mappings values('1-go Maja', '1 Maja') on conflict do nothing;
insert into street_names_mappings values('1-ego Maja', '1 Maja') on conflict do nothing;
insert into street_names_mappings values('11-go Listopada', '11 Listopada') on conflict do nothing;
insert into street_names_mappings values('15-go Grudnia', '15 Grudnia') on conflict do nothing;
insert into street_names_mappings values('17-go Lipca', '17 Lipca') on conflict do nothing;
insert into street_names_mappings values('21-go Stycznia', '21 Stycznia') on conflict do nothing;
insert into street_names_mappings values('24-go Stycznia', '24 Stycznia') on conflict do nothing;
insert into street_names_mappings values('27-go Stycznia', '27 Stycznia') on conflict do nothing;
insert into street_names_mappings values('28-go Lutego', '28 Lutego') on conflict do nothing;
insert into street_names_mappings values('3-go Kwietnia', '3 Kwietnia') on conflict do nothing;
insert into street_names_mappings values('3-go Maja', '3 Maja') on conflict do nothing;
insert into street_names_mappings values('3-ego Maja', '3 Maja') on conflict do nothing;
insert into street_names_mappings values('35 Lecia PRL', '35-lecia PRL') on conflict do nothing;
insert into street_names_mappings values('9-go Maja', '9 Maja') on conflict do nothing;
insert into street_names_mappings values('Abramskiego J. ks.', 'Księdza Jana Abramskiego') on conflict do nothing;
insert into street_names_mappings values('Al. H. Kołłątaja', 'Aleja Hugona Kołłątaja') on conflict do nothing;
insert into street_names_mappings values('Al. Spacerowa', 'aleja Spacerowa') on conflict do nothing;
insert into street_names_mappings values('Al. Wodniaków', 'Aleja Wodniaków') on conflict do nothing;
insert into street_names_mappings values('Andersa Władysława', 'Władysława Andersa') on conflict do nothing;
insert into street_names_mappings values('Arciszewskiego Krzysztofa', 'Krzysztofa  Arciszewskiego') on conflict do nothing;
insert into street_names_mappings values('Asnyka A.', 'Adama Asnyka') on conflict do nothing;
insert into street_names_mappings values('Asnyka Adama', 'Adama Asnyka') on conflict do nothing;
insert into street_names_mappings values('Asnyka', 'Adama Asnyka') on conflict do nothing;
insert into street_names_mappings values('Baczewskiego Jana', 'Jana Baczewskiego') on conflict do nothing;
insert into street_names_mappings values('Baczyńskiego K. K.', 'Krzysztofa Kamila Baczyńskiego') on conflict do nothing;
insert into street_names_mappings values('Baczyńskiego', 'Krzysztofa Kamila Baczyńskiego') on conflict do nothing;
insert into street_names_mappings values('Barlickiego Norberta', 'Norberta Barlickiego') on conflict do nothing;
insert into street_names_mappings values('Barlickiego', 'Norberta Barlickiego') on conflict do nothing;
insert into street_names_mappings values('Bauera Jana', 'Jana Bauera') on conflict do nothing;
insert into street_names_mappings values('Bałasza A.', 'Aleksandra Bałasza') on conflict do nothing;
insert into street_names_mappings values('Bema Józefa', 'Józefa Bema') on conflict do nothing;
insert into street_names_mappings values('Bema', 'Józefa Bema') on conflict do nothing;
insert into street_names_mappings values('Boguckiego', 'Teofila Boguckiego') on conflict do nothing;
insert into street_names_mappings values('Boh. Stalingradu', 'Bohaterów Stalingradu') on conflict do nothing;
insert into street_names_mappings values('Boh. Warszawy', 'Bohaterów Warszawy') on conflict do nothing;
insert into street_names_mappings values('Bojara-Fijałkowskiego Gracjana', 'Gracjana Bojara-Fijałkowskiego') on conflict do nothing;
insert into street_names_mappings values('Bora-Komorowskiego T. gen.', 'Generała Tadeusza Bora-Komorowskiego') on conflict do nothing;
insert into street_names_mappings values('Borzymowskiego Marcina', 'Marcina Borzymowskiego') on conflict do nothing;
insert into street_names_mappings values('Boya Żeleńskiego', 'Tadeusza Boya-Żeleńskiego') on conflict do nothing;
insert into street_names_mappings values('Boya-Żeleńskiego Tadeusza', 'Tadeusza Boya-Żeleńskiego') on conflict do nothing;
insert into street_names_mappings values('Bożka Arkadiusza', 'Arkadiusza Bożka') on conflict do nothing;
insert into street_names_mappings values('Broniewskiego W.', 'Władysława Broniewskiego') on conflict do nothing;
insert into street_names_mappings values('Broniewskiego Władysława', 'Władysława Broniewskiego') on conflict do nothing;
insert into street_names_mappings values('Broniewskiego', 'Władysława Broniewskiego') on conflict do nothing;
insert into street_names_mappings values('Brzechwy J.', 'Jana Brzechwy') on conflict do nothing;
insert into street_names_mappings values('Brzechwy Jana', 'Jana Brzechwy') on conflict do nothing;
insert into street_names_mappings values('Brzechwy', 'Jana Brzechwy') on conflict do nothing;
insert into street_names_mappings values('Buczka M.', 'Mariana Buczka') on conflict do nothing;
insert into street_names_mappings values('Buczka', 'Mariana Buczka') on conflict do nothing;
insert into street_names_mappings values('Chałubińskiego Tytusa', 'Tytusa Chałubińskiego') on conflict do nothing;
insert into street_names_mappings values('Chełmońskiego J.', 'Józefa Chełmońskiego') on conflict do nothing;
insert into street_names_mappings values('Chełmońskiego Józefa', 'Józefa Chełmońskiego') on conflict do nothing;
insert into street_names_mappings values('Chodkiewicza Jana', 'Jana Chodkiewicza') on conflict do nothing;
insert into street_names_mappings values('Chodkiewicza Karola', 'Karola Chodkiewicza') on conflict do nothing;
insert into street_names_mappings values('Chodkiewicza', 'Karola Chodkiewicza') on conflict do nothing;
insert into street_names_mappings values('Chopina F.', 'Fryderyka Chopina') on conflict do nothing;
insert into street_names_mappings values('Chopina Fryderyka', 'Fryderyka Chopina') on conflict do nothing;
insert into street_names_mappings values('Chopina', 'Fryderyka Chopina') on conflict do nothing;
insert into street_names_mappings values('Chrobrego B.', 'Bolesława Chrobrego') on conflict do nothing;
insert into street_names_mappings values('Chrobrego', 'Bolesława Chrobrego') on conflict do nothing;
insert into street_names_mappings values('Chrzanowskiego Ignacego', 'Ignacego Chrzanowskiego') on conflict do nothing;
insert into street_names_mappings values('Cieślaka W.', 'Cieślaka W.') on conflict do nothing;
insert into street_names_mappings values('Ciołkowskiego', 'Konstantego Ciołkowskiego') on conflict do nothing;
insert into street_names_mappings values('Conrada Korzeniowskiego Josepha', 'Josepha Conrada Korzeniowskiego') on conflict do nothing;
insert into street_names_mappings values('Curie-Skłodowskiej', 'Marii Curie-Skłodowskiej') on conflict do nothing;
insert into street_names_mappings values('Czarnieckiego S.', 'Stefana Czarnieckiego') on conflict do nothing;
insert into street_names_mappings values('Czarnieckiego Stefana', 'Stefana Czarnieckiego') on conflict do nothing;
insert into street_names_mappings values('Daszyńskiego I.', 'Ignacego Daszyńskiego') on conflict do nothing;
insert into street_names_mappings values('Daszyńskiego', 'Ignacego Daszyńskiego') on conflict do nothing;
insert into street_names_mappings values('Derdowskiego', 'Hieronima Derdowskiego') on conflict do nothing;
insert into street_names_mappings values('Dmowskiego Romana', 'Romana Dmowskiego') on conflict do nothing;
insert into street_names_mappings values('Domańskiego Bolesława', 'Bolesława Domańskiego') on conflict do nothing;
insert into street_names_mappings values('Domina Czesława', 'Czesława Domina') on conflict do nothing;
insert into street_names_mappings values('Drzymały M.', 'Michała Drzymały') on conflict do nothing;
insert into street_names_mappings values('Drzymały Michała', 'Michała Drzymały') on conflict do nothing;
insert into street_names_mappings values('Dubois Stanisława', 'Stanisława Dubois') on conflict do nothing;
insert into street_names_mappings values('Dunikowskiego K.', 'Ksawerego Dunikowskiego') on conflict do nothing;
insert into street_names_mappings values('Dzierżykraja-Morawskiego J. W.', 'Witolda Józefa Dzierżykraja-Morawskiego') on conflict do nothing;
insert into street_names_mappings values('Dąbka Stanisława', 'Stanisława Dąbka') on conflict do nothing;
insert into street_names_mappings values('Dąbrowskiego J. Ks.', 'Księdza Józefa Dąbrowskiego') on conflict do nothing;
insert into street_names_mappings values('Dąbrowskiego J.', 'Jarosława Dąbrowskiego') on conflict do nothing;
insert into street_names_mappings values('Dąbrowskiego Jarosława', 'Jarosława Dąbrowskiego') on conflict do nothing;
insert into street_names_mappings values('Dąbrowskiej M.', 'Marii Dąbrowskiej') on conflict do nothing;
insert into street_names_mappings values('Długosza J.', 'Jana Długosza') on conflict do nothing;
insert into street_names_mappings values('F. Szopena', 'Fryderyka Chopina') on conflict do nothing;
insert into street_names_mappings values('Fałata Juliana', 'Juliana Fałata') on conflict do nothing;
insert into street_names_mappings values('Fitelberga', 'Grzegorza Fitelberga') on conflict do nothing;
insert into street_names_mappings values('Fitio Jerzego', 'Jerzego Fitio') on conflict do nothing;
insert into street_names_mappings values('Fornalskiej', 'Małgorzaty Fornalskiej') on conflict do nothing;
insert into street_names_mappings values('Frankowskiego Jana', 'Jana Frankowskiego') on conflict do nothing;
insert into street_names_mappings values('Fredry Aleksandra', 'Aleksandra Fredry') on conflict do nothing;
insert into street_names_mappings values('Fredry', 'Aleksandra Fredry') on conflict do nothing;
insert into street_names_mappings values('Gałczyńskiego K. I. ', 'Konstantego Ildefonsa Gałczyńskiego') on conflict do nothing;
insert into street_names_mappings values('Gałczyńskiego Konstantego Ildefonsa', 'Konstantego Ildefonsa Gałczyńskiego') on conflict do nothing;
insert into street_names_mappings values('Gałczyńskiego', 'Konstantego Ildefonsa Gałczyńskiego') on conflict do nothing;
insert into street_names_mappings values('gen. Grota Roweckiego', 'Gererała Stefana Grota Roweckiego') on conflict do nothing;
insert into street_names_mappings values('Głowackiego A.', 'Aleksandra Głowackiego') on conflict do nothing;
insert into street_names_mappings values('Gierczak Emilii', 'Emilii Gierczak') on conflict do nothing;
insert into street_names_mappings values('Gierymskich Aleksandra i Maksymiliana', 'Aleksandra i Maksymiliana Gierymskich') on conflict do nothing;
insert into street_names_mappings values('Golisza Maksymiliana', 'Maksymiliana Golisza') on conflict do nothing;
insert into street_names_mappings values('Grabskiego Wł.', 'Władysława Grabskiego') on conflict do nothing;
insert into street_names_mappings values('Grochowskiego Maksymiliana', 'Maksymiliana Grochowskiego') on conflict do nothing;
insert into street_names_mappings values('Grota Roweckiego S. gen.', 'Gererała Stefana Grota Roweckiego') on conflict do nothing;
insert into street_names_mappings values('Grottgera A.', 'Artura Grottgera') on conflict do nothing;
insert into street_names_mappings values('Grottgera Artura', 'Artura Grottgera') on conflict do nothing;
insert into street_names_mappings values('Górskiego Klaudiusza', 'Klaudiusza Górskiego') on conflict do nothing;
insert into street_names_mappings values('Gąszczak Marii Magdaleny', 'Marii Magdaleny Gąszczak') on conflict do nothing;
insert into street_names_mappings values('Głowackiego B.', 'Bartosza Głowackiego') on conflict do nothing;
insert into street_names_mappings values('Głowackiego Bartosza', 'Bartosza Głowackiego') on conflict do nothing;
insert into street_names_mappings values('Hirszfelda L.', 'Ludwika Hirszfelda') on conflict do nothing;
insert into street_names_mappings values('I Armii W.P.', 'I Armii Wojska Polskiego') on conflict do nothing;
insert into street_names_mappings values('Iwaszkiewicza J.', 'Jarosława Iwaszkiewicza') on conflict do nothing;
insert into street_names_mappings values('J. Kochanowskiego', 'Jana Kochanowskiego') on conflict do nothing;
insert into street_names_mappings values('Jagiełły W.', 'Władysława Jagiełły') on conflict do nothing;
insert into street_names_mappings values('Jagiełły', 'Władysława Jagiełły') on conflict do nothing;
insert into street_names_mappings values('Jagoszewskiego Henryka', 'Henryka Jagoszewskiego') on conflict do nothing;
insert into street_names_mappings values('Jankiel', 'Jankiela') on conflict do nothing;
insert into street_names_mappings values('Jelec Jadwigi', 'Jadwigi Jelec') on conflict do nothing;
insert into street_names_mappings values('Jordana Henryka', 'Henryka Jordana') on conflict do nothing;
insert into street_names_mappings values('Joselewicza', 'Berka Joselewicza') on conflict do nothing;
insert into street_names_mappings values('Jurkiewicza Kazimierza', 'Kazimierza Jurkiewicza') on conflict do nothing;
insert into street_names_mappings values('Kajki Michała', 'Michała Kajki') on conflict do nothing;
insert into street_names_mappings values('Kamińskiego A.', 'Aleksandra Kamińskiego') on conflict do nothing;
insert into street_names_mappings values('Karłowicza Mieczysława', 'Mieczysława Karłowicza') on conflict do nothing;
insert into street_names_mappings values('Karłowicza', 'Mieczysława Karłowicza') on conflict do nothing;
insert into street_names_mappings values('Kasprowicza J.', 'Jana Kasprowicza') on conflict do nothing;
insert into street_names_mappings values('Kasprowicza Jana', 'Jana Kasprowicza') on conflict do nothing;
insert into street_names_mappings values('Kilińskiego J.', 'Jana Kilińskiego') on conflict do nothing;
insert into street_names_mappings values('Kilińskiego Jana', 'Jana Kilińskiego') on conflict do nothing;
insert into street_names_mappings values('Kilińskiego', 'Jana Kilińskiego') on conflict do nothing;
insert into street_names_mappings values('Kinga Martina', 'Martina Kinga') on conflict do nothing;
insert into street_names_mappings values('Klemensiewicza Zenona', 'Zenona Klemensiewicza') on conflict do nothing;
insert into street_names_mappings values('Kmicica Andrzeja', 'Andrzeja Kmicica') on conflict do nothing;
insert into street_names_mappings values('Kniewskiego Władysława', 'Władysława Kniewskiego') on conflict do nothing;
insert into street_names_mappings values('Kochanowskiego J.', 'Jana Kochanowskiego') on conflict do nothing;
insert into street_names_mappings values('Kochanowskiego Jana', 'Jana Kochanowskiego') on conflict do nothing;
insert into street_names_mappings values('Kolumba Krzysztofa', 'Krzysztofa Kolumba') on conflict do nothing;
insert into street_names_mappings values('Koniecpolskiego Stanisława', 'Stanisława Koniecpolskiego') on conflict do nothing;
insert into street_names_mappings values('Konopnickiej M.', 'Marii Konopnickiej') on conflict do nothing;
insert into street_names_mappings values('Konopnickiej Marii', 'Marii Konopnickiej') on conflict do nothing;
insert into street_names_mappings values('Konopnickiej', 'Marii Konopnickiej') on conflict do nothing;
insert into street_names_mappings values('Kopernika M.', 'Mikołaja Kopernika') on conflict do nothing;
insert into street_names_mappings values('Kopernika Mikołaja', 'Mikołaja Kopernika') on conflict do nothing;
insert into street_names_mappings values('Kopernika', 'Mikołaja Kopernika') on conflict do nothing;
insert into street_names_mappings values('Korczaka J. dr', 'Doktora Janusza Korczaka') on conflict do nothing;
insert into street_names_mappings values('Korczaka Janusza', 'Janusza Korczaka') on conflict do nothing;
insert into street_names_mappings values('Korczaka', 'Janusza Korczaka') on conflict do nothing;
insert into street_names_mappings values('Korfantego W.', 'Wojciecha Korfantego') on conflict do nothing;
insert into street_names_mappings values('Kossaka Juliusza', 'Juliusza Kossaka') on conflict do nothing;
insert into street_names_mappings values('Kostenckiego Jerzego', 'Jerzego Kostenckiego') on conflict do nothing;
insert into street_names_mappings values('Kostrzewy Wery', 'Wery Kostrzewy') on conflict do nothing;
insert into street_names_mappings values('Kotarbińskiego Tadeusza', 'Tadeusza Kotarbińskiego') on conflict do nothing;
insert into street_names_mappings values('Kołłątaja H.', 'Hugona Kołłątaja') on conflict do nothing;
insert into street_names_mappings values('Kołłątaja Hugo', 'Hugona Kołłątaja') on conflict do nothing;
insert into street_names_mappings values('Kołłątaja', 'Hugona Kołłątaja') on conflict do nothing;
insert into street_names_mappings values('Kościuszki T. gen.', 'Generała Tadeusza Kościuszki') on conflict do nothing;
insert into street_names_mappings values('Kościuszki T.', 'Tadeusza Kościuszki') on conflict do nothing;
insert into street_names_mappings values('Kościuszki Tadeusza', 'Tadeusza Kościuszki') on conflict do nothing;
insert into street_names_mappings values('Kościuszki', 'Tadeusza Kościuszki') on conflict do nothing;
insert into street_names_mappings values('Kr. Jadwigi', 'Królowej Jadwigi') on conflict do nothing;
insert into street_names_mappings values('Krasickiego Ignacego', 'Ignacego Krasickiego') on conflict do nothing;
insert into street_names_mappings values('Krasińskiego Z.', 'Zygmunta Krasińskiego') on conflict do nothing;
insert into street_names_mappings values('Kraszewskiego J. I.', 'Józefa Ignacego Kraszewskiego') on conflict do nothing;
insert into street_names_mappings values('Kromera J.', 'Józefa Kromera') on conflict do nothing;
insert into street_names_mappings values('Kruczkowskiego L.', 'Leona Kruczkowskiego') on conflict do nothing;
insert into street_names_mappings values('Krzyżanowskiego Juliana', 'Juliana Krzyżanowskiego') on conflict do nothing;
insert into street_names_mappings values('Ks. Elżbiety', 'Księżnej Elżbiety') on conflict do nothing;
insert into street_names_mappings values('Kuczkowskiego Ignacego', 'Ignacego Kuczkowskiego') on conflict do nothing;
insert into street_names_mappings values('Kurpińskiego Karola', 'Karola Kurpińskiego') on conflict do nothing;
insert into street_names_mappings values('Kusocińskiego J.', 'Janusza Kusocińskiego') on conflict do nothing;
insert into street_names_mappings values('Kutrzeby Tadeusza', 'Tadeusza Kutrzeby') on conflict do nothing;
insert into street_names_mappings values('Kwiatkowskiego Eugeniusza', 'Eugeniusza Kwiatkowskiego') on conflict do nothing;
insert into street_names_mappings values('Lange Oskara', 'Oskara Lange') on conflict do nothing;
insert into street_names_mappings values('Laskonogiego Władysława', 'Władysława Laskonogiego') on conflict do nothing;
insert into street_names_mappings values('Lelewela Joachima', 'Joachima Lelewela') on conflict do nothing;
insert into street_names_mappings values('Leśmiana B.', 'Bolesława Leśmiana') on conflict do nothing;
insert into street_names_mappings values('Limanowskiego B.', 'Bolesława Limanowskiego') on conflict do nothing;
insert into street_names_mappings values('Limanowskiego Bolesława', 'Bolesława Limanowskiego') on conflict do nothing;
insert into street_names_mappings values('M. Konopnickiej', 'Marii Konopnickiej') on conflict do nothing;
insert into street_names_mappings values('Maciejewicza Konstantego', 'Konstantego Maciejewicza') on conflict do nothing;
insert into street_names_mappings values('Makowskiego Tadeusza', 'Tadeusza Makowskiego') on conflict do nothing;
insert into street_names_mappings values('Makuszyńskiego Kornela', 'Kornela Makuszyńskiego') on conflict do nothing;
insert into street_names_mappings values('Malczewskiego Jacka', 'Jacka Malczewskiego') on conflict do nothing;
insert into street_names_mappings values('Malczewskiego J.', 'Jacka Malczewskiego') on conflict do nothing;
insert into street_names_mappings values('Matejki ', 'Jana Matejki') on conflict do nothing;
insert into street_names_mappings values('Matejki J.', 'Jana Matejki') on conflict do nothing;
insert into street_names_mappings values('Matejki Jana', 'Jana Matejki') on conflict do nothing;
insert into street_names_mappings values('Matejki', 'Jana Matejki') on conflict do nothing;
insert into street_names_mappings values('Matusewicz G. dr', 'Doktor Genowefy Matusewicz') on conflict do nothing;
insert into street_names_mappings values('Maćkowicza Izydora', 'Izydora Maćkowicza') on conflict do nothing;
insert into street_names_mappings values('Meczenników Unickich', 'Męczenników Unickich') on conflict do nothing;
insert into street_names_mappings values('Miarki K.', 'Karola Miarki') on conflict do nothing;
insert into street_names_mappings values('Michałowskiego Piotra', 'Piotra Michałowskiego') on conflict do nothing;
insert into street_names_mappings values('Mickiewicza A.', 'Adama Mickiewicza') on conflict do nothing;
insert into street_names_mappings values('Mickiewicza Adama', 'Adama Mickiewicza') on conflict do nothing;
insert into street_names_mappings values('Mickiewicza', 'Adama Mickiewicza') on conflict do nothing;
insert into street_names_mappings values('Mireckiego Józefa', 'Józefa Mireckiego') on conflict do nothing;
insert into street_names_mappings values('Miłosza C.', 'Czesława Miłosza') on conflict do nothing;
insert into street_names_mappings values('Miłosza Cz.', 'Czesława Miłosza') on conflict do nothing;
insert into street_names_mappings values('Modrzejewskiej Heleny', 'Heleny Modrzejewskiej') on conflict do nothing;
insert into street_names_mappings values('Moniuszki S.', 'Stanisława Moniuszki') on conflict do nothing;
insert into street_names_mappings values('Moniuszki Stanisława', 'Stanisława Moniuszki') on conflict do nothing;
insert into street_names_mappings values('Moniuszki', 'Stanisława Moniuszki') on conflict do nothing;
insert into street_names_mappings values('Morcinka G.', 'Gustawa Morcinka') on conflict do nothing;
insert into street_names_mappings values('Morcinka Gustawa', 'Gustawa Morcinka') on conflict do nothing;
insert into street_names_mappings values('Narutowicza G.', 'Gabriela Narutowicza') on conflict do nothing;
insert into street_names_mappings values('Narutowicza Gabriela', 'Gabriela Narutowicza') on conflict do nothing;
insert into street_names_mappings values('Narutowicza', 'Gabriela Narutowicza') on conflict do nothing;
insert into street_names_mappings values('Nałkowskiej', 'Zofii Nałkowskiej') on conflict do nothing;
insert into street_names_mappings values('Nałkowskiej Z.', 'Zofii Nałkowskiej') on conflict do nothing;
insert into street_names_mappings values('Nerudy Pablo', 'Pablo Nerudy') on conflict do nothing;
insert into street_names_mappings values('Niemcewicza', 'Juliana Ursyna Niemcewicza') on conflict do nothing;
insert into street_names_mappings values('Norwida C. K. ', 'Cypriana Kamila Norwida') on conflict do nothing;
insert into street_names_mappings values('Norwida C.K.', 'Cypriana Kamila Norwida') on conflict do nothing;
insert into street_names_mappings values('Norwida Cypriana', 'Cypriana Norwida') on conflict do nothing;
insert into street_names_mappings values('Norwida', 'Cypriana Kamila Norwida') on conflict do nothing;
insert into street_names_mappings values('Noskowskiego Zygmunta', 'Zygmunta Noskowskiego') on conflict do nothing;
insert into street_names_mappings values('Nowotki M.', 'Marcelego Nowotki') on conflict do nothing;
insert into street_names_mappings values('Nowotki', 'Marcelego Nowotki') on conflict do nothing;
insert into street_names_mappings values('Nowowiejskiego Feliksa', 'Feliksa Nowowiejskiego') on conflict do nothing;
insert into street_names_mappings values('Ogińskiego Michała Kleofasa', 'Michała Kleofasa Ogińskiego') on conflict do nothing;
insert into street_names_mappings values('Ogińskiego Michała', 'Michała Ogińskiego') on conflict do nothing;
insert into street_names_mappings values('Okrzei S.', 'Stefana Okrzei') on conflict do nothing;
insert into street_names_mappings values('Okrzei St.', 'Stefana Okrzei') on conflict do nothing;
insert into street_names_mappings values('Okrzei Stefana', 'Stefana Okrzei') on conflict do nothing;
insert into street_names_mappings values('Okulickiego Leopolda', 'Leopolda Okulickiego') on conflict do nothing;
insert into street_names_mappings values('Okulickiego Niedźwiadka L. gen.', 'Generała Leopolda Okulickiego Niedźwiadka') on conflict do nothing;
insert into street_names_mappings values('Ordona J.', 'Juliana Ordona') on conflict do nothing;
insert into street_names_mappings values('Orkana W.', 'Władysława Orkana') on conflict do nothing;
insert into street_names_mappings values('Orzeszkowej E.', 'Elizy Orzeszkowej') on conflict do nothing;
insert into street_names_mappings values('Orzeszkowej', 'Elizy Orzeszkowej') on conflict do nothing;
insert into street_names_mappings values('Orłowskiego Aleksandra', 'Aleksandra Orłowskiego') on conflict do nothing;
insert into street_names_mappings values('Paderewskiego Ignacego Jana', 'Ignacego Jana Paderewskiego') on conflict do nothing;
insert into street_names_mappings values('Paderewskiego Ignacego', 'Ignacego Jana Paderewskiego') on conflict do nothing;
insert into street_names_mappings values('Paderewskiego', 'Ignacego Paderewskiego') on conflict do nothing;
insert into street_names_mappings values('Picassa Pablo', 'Pablo Picassa') on conflict do nothing;
insert into street_names_mappings values('Pieniężnego Seweryna', 'Seweryna Pieniężnego') on conflict do nothing;
insert into street_names_mappings values('Pileckiego Witolda', 'Witolda Pileckiego') on conflict do nothing;
insert into street_names_mappings values('Piłsudskiego J. Marsz.', 'Marszałka Józefa Piłsudskiego') on conflict do nothing;
insert into street_names_mappings values('Piłsudskiego J. marsz.', 'Marszałka Józefa Piłsudskiego') on conflict do nothing;
insert into street_names_mappings values('Piłsudskiego J.', 'Józefa Piłsudskiego') on conflict do nothing;
insert into street_names_mappings values('Piłsudskiego Józefa', 'Józefa Piłsudskiego') on conflict do nothing;
insert into street_names_mappings values('Piłsudskiego Marszałka', 'Marszałka Józefa Piłsudskiego') on conflict do nothing;
insert into street_names_mappings values('Piłsudskiego', 'Józefa Piłsudskiego') on conflict do nothing;
insert into street_names_mappings values('Plater E.', 'Emilii Plater E.') on conflict do nothing;
insert into street_names_mappings values('Pobożnego H.', 'Henryka Pobożnego') on conflict do nothing;
insert into street_names_mappings values('Polipol Aleja', 'Aleja Polipol') on conflict do nothing;
insert into street_names_mappings values('Poniatowskiego J.', 'Józefa Poniatowskiego') on conflict do nothing;
insert into street_names_mappings values('Popiełuszki Jerzego', 'Jerzego Popiełuszki') on conflict do nothing;
insert into street_names_mappings values('Powstańców Wlkp.', 'Powstańców Wielkopolskich') on conflict do nothing;
insert into street_names_mappings values('Poświatowskiej H.', 'Haliny Poświatowskiej') on conflict do nothing;
insert into street_names_mappings values('Prusa B.', 'Bolesława Prusa') on conflict do nothing;
insert into street_names_mappings values('Prusa Bolesława', 'Bolesława Prusa') on conflict do nothing;
insert into street_names_mappings values('Próchnika Adama', 'Adama Próchnika') on conflict do nothing;
insert into street_names_mappings values('Przerwy-Tetmajera K.', 'Kazimierza Przerwy-Tetmajera') on conflict do nothing;
insert into street_names_mappings values('Pstrowskiego', 'Wincentego Pstrowskiego') on conflict do nothing;
insert into street_names_mappings values('Pułaskiego K.', 'Kazimierza Pułaskiego') on conflict do nothing;
insert into street_names_mappings values('Rafińskiego Teodora', 'Teodora Rafińskiego') on conflict do nothing;
insert into street_names_mappings values('Rataja M.', 'Macieja Rataja') on conflict do nothing;
insert into street_names_mappings values('Ratajczaka Franciszka', 'Franciszka Ratajczaka') on conflict do nothing;
insert into street_names_mappings values('Reja M.', 'Mikołaja Reja') on conflict do nothing;
insert into street_names_mappings values('Reja Mikołaja', 'Mikołaja Reja') on conflict do nothing;
insert into street_names_mappings values('Reja', 'Mikołaja Reja') on conflict do nothing;
insert into street_names_mappings values('Rejtana Tadeusza', 'Tadeusza Rejtana') on conflict do nothing;
insert into street_names_mappings values('Rejtana', 'Tadeusza Rejtana') on conflict do nothing;
insert into street_names_mappings values('Reymonta W.', 'Władysława Reymonta') on conflict do nothing;
insert into street_names_mappings values('Reymonta W. S.', 'Władysława Stanisława Reymonta') on conflict do nothing;
insert into street_names_mappings values('Reymonta Władysława Stanisława', 'Władysława Stanisława Reymonta') on conflict do nothing;
insert into street_names_mappings values('Reymonta Władysława', 'Władysława Reymonta') on conflict do nothing;
insert into street_names_mappings values('Reymonta', 'Władysława Reymonta') on conflict do nothing;
insert into street_names_mappings values('Rodziewiczówny Marii', 'Marii Rodziewiczówny') on conflict do nothing;
insert into street_names_mappings values('Roli-Żymierskiego M. marsz.', 'Marszałka Michała Roli-Żymierskiego') on conflict do nothing;
insert into street_names_mappings values('Roosevelta', 'Franklina Delano Roosevelta') on conflict do nothing;
insert into street_names_mappings values('Ruszczyca Ferdynanda', 'Ferdynanda Ruszczyca') on conflict do nothing;
insert into street_names_mappings values('Rzeckiego I.', 'Ignacego Rzeckiego') on conflict do nothing;
insert into street_names_mappings values('Rzeckiego', 'Ignacego Rzeckiego') on conflict do nothing;
insert into street_names_mappings values('Różyckiego Ludomira', 'Ludomira Różyckiego') on conflict do nothing;
insert into street_names_mappings values('Sanguszki A. ks.', 'Księcia Andrzeja Sanguszki') on conflict do nothing;
insert into street_names_mappings values('Sawickiej H.', 'Hanki Sawickiej') on conflict do nothing;
insert into street_names_mappings values('Sawickiej Hanki', 'Hanki Sawickiej') on conflict do nothing;
insert into street_names_mappings values('Sienkiewicza H.', 'Henryka Sienkiewicza') on conflict do nothing;
insert into street_names_mappings values('Sienkiewicza Henryka', 'Henryka Sienkiewicza') on conflict do nothing;
insert into street_names_mappings values('Sienkiewicza', 'Henryka Sienkiewicza') on conflict do nothing;
insert into street_names_mappings values('Siennickiego Ryszarda', 'Ryszarda Siennickiego') on conflict do nothing;
insert into street_names_mappings values('Sierocińskiego Romana', 'Romana Sierocińskiego') on conflict do nothing;
insert into street_names_mappings values('Sierpińskiego Wacława', 'Wacława Sierpińskiego') on conflict do nothing;
insert into street_names_mappings values('Sierpińskiego Z. prof.', 'Profesora Zbigniewa Sierpińskiego') on conflict do nothing;
insert into street_names_mappings values('Sikorskiego W. gen.', 'Generała Władysława Sikorskiego') on conflict do nothing;
insert into street_names_mappings values('Sikorskiego W.', 'Władysława Sikorskiego') on conflict do nothing;
insert into street_names_mappings values('Sikorskiego Władysława', 'Władysława Sikorskiego') on conflict do nothing;
insert into street_names_mappings values('Skargi P.', 'Piora Skargi') on conflict do nothing;
insert into street_names_mappings values('Skargi Piotra', 'Piotra Skargi') on conflict do nothing;
insert into street_names_mappings values('Skoczylasa Władysława', 'Władysława Skoczylasa') on conflict do nothing;
insert into street_names_mappings values('Skrzetuskiego J.', 'Jana Skrzetuskiego') on conflict do nothing;
insert into street_names_mappings values('Skrzetuskiego Jana', 'Jana Skrzetuskiego') on conflict do nothing;
insert into street_names_mappings values('Skłodowskiej', 'Marii Skłodowskiej') on conflict do nothing;
insert into street_names_mappings values('Skłodowskiej- Curie M.', 'Marii Skłodowskiej-Curie') on conflict do nothing;
insert into street_names_mappings values('Skłodowskiej-Curie M.', 'Marii Skłodowskiej-Curie') on conflict do nothing;
insert into street_names_mappings values('Skłodowskiej-Curie Marii', 'Marii Skłodowskiej-Curie') on conflict do nothing;
insert into street_names_mappings values('Skłodowskiej-Curie', 'Marii Skłodowskiej-Curie') on conflict do nothing;
insert into street_names_mappings values('Sokołowskiego A.', 'Alfreda Sokołowskiego') on conflict do nothing;
insert into street_names_mappings values('Soplicy J.', 'Jacka Soplicy') on conflict do nothing;
insert into street_names_mappings values('Sowińskiego Józefa', 'Józefa Sowińskiego') on conflict do nothing;
insert into street_names_mappings values('Spasowskiego Władysława', 'Władysława Spasowskiego') on conflict do nothing;
insert into street_names_mappings values('Staffa Leopolda', 'Leopolda Staffa') on conflict do nothing;
insert into street_names_mappings values('Staffa', 'Leopolda Staffa') on conflict do nothing;
insert into street_names_mappings values('Stankiewicza Mamerta', 'Mamerta Stankiewicza') on conflict do nothing;
insert into street_names_mappings values('Starzyńskiego Stefana', 'Stefana Starzyńskiego') on conflict do nothing;
insert into street_names_mappings values('Staszica St.', 'Stanisława Staszica') on conflict do nothing;
insert into street_names_mappings values('Staszica S.', 'Stanisława Staszica') on conflict do nothing;
insert into street_names_mappings values('Staszica Stanisława', 'Stanisława Staszica') on conflict do nothing;
insert into street_names_mappings values('Staszica', 'Stanisława Staszica') on conflict do nothing;
insert into street_names_mappings values('Struga Andrzeja', 'Andrzeja Struga') on conflict do nothing;
insert into street_names_mappings values('Struka Księdza', 'Księdza Struka') on conflict do nothing;
insert into street_names_mappings values('Stryjeńskiej Z.', 'Zofii Stryjeńskiej') on conflict do nothing;
insert into street_names_mappings values('Stwosza W.', 'Wita Stwosza') on conflict do nothing;
insert into street_names_mappings values('Sucharskiego Henryka', 'Henryka Sucharskiego') on conflict do nothing;
insert into street_names_mappings values('Sułkowskiego Antoniego', 'Antoniego Sułkowskiego') on conflict do nothing;
insert into street_names_mappings values('Sygietyńskiego Tadeusza', 'Tadeusza Sygietyńskiego') on conflict do nothing;
insert into street_names_mappings values('Szafera W. prof.', 'Profesora Władysława Szafera') on conflict do nothing;
insert into street_names_mappings values('Szarego F.', 'Floriana Szarego') on conflict do nothing;
insert into street_names_mappings values('Szelburg-Zarembiny Ewy', 'Ewy Szelburg-Zarembiny') on conflict do nothing;
insert into street_names_mappings values('Szenwalda Lucjana', 'Lucjana Szenwalda') on conflict do nothing;
insert into street_names_mappings values('Szymanowskiego Karola', 'Karola Szymanowskiego') on conflict do nothing;
insert into street_names_mappings values('Szymanowskiego', 'Karola Szymanowskiego') on conflict do nothing;
insert into street_names_mappings values('Słowackiego J.', 'Juliusza Słowackiego') on conflict do nothing;
insert into street_names_mappings values('Słowackiego Juliusza', 'Juliusza Słowackiego') on conflict do nothing;
insert into street_names_mappings values('Słowackiego', 'Juliusza Słowackiego') on conflict do nothing;
insert into street_names_mappings values('T. Kościuszki', 'Tadeusza Kościuszki') on conflict do nothing;
insert into street_names_mappings values('Tarnowskiego Jana', 'Jana Tarnowskiego') on conflict do nothing;
insert into street_names_mappings values('Tatarkiewicza Władysława', 'Władysława Tatarkiewicza') on conflict do nothing;
insert into street_names_mappings values('Teligi Leonida', 'Leonida Teligi') on conflict do nothing;
insert into street_names_mappings values('Teligi', 'Leonida Teligi') on conflict do nothing;
insert into street_names_mappings values('Tetmajera Kazimierza', 'Kazimierza Tetmajera') on conflict do nothing;
insert into street_names_mappings values('Tetmajera', 'Kazimierza Tetmajera') on conflict do nothing;
insert into street_names_mappings values('Tokarzewskiego-Karaszewicza Torwida M. gen.', 'Generała Michała Torwida Tokarzewskiego-Karaszewicza') on conflict do nothing;
insert into street_names_mappings values('Traugutta Romualda', 'Romualda Traugutta') on conflict do nothing;
insert into street_names_mappings values('Traugutta R.', 'Romualda Traugutta') on conflict do nothing;
insert into street_names_mappings values('Traugutta', 'Romualda Traugutta') on conflict do nothing;
insert into street_names_mappings values('Turowskiego Władysława', 'Władysława Turowskiego') on conflict do nothing;
insert into street_names_mappings values('Tuwima J.', 'Juliana Tuwima') on conflict do nothing;
insert into street_names_mappings values('Tuwima Juliana', 'Juliana Tuwima') on conflict do nothing;
insert into street_names_mappings values('Tuwima', 'Juliana Tuwima') on conflict do nothing;
insert into street_names_mappings values('Tysiąclecia PP', 'Tysiąclecia Państwa Polskiego') on conflict do nothing;
insert into street_names_mappings values('W. Jagiełły', 'Władysława Jagiełły') on conflict do nothing;
insert into street_names_mappings values('Wallenroda K.', 'Konrada Wallenroda') on conflict do nothing;
insert into street_names_mappings values('Waresiaka E. Ks.', 'Księdza Eugeniusza Waresiaka') on conflict do nothing;
insert into street_names_mappings values('Warskiego Adolfa', 'Adolfa Warskiego') on conflict do nothing;
insert into street_names_mappings values('Waryńskiego L.', 'Ludwika Waryńskiego') on conflict do nothing;
insert into street_names_mappings values('Waryńskiego Ludwika', 'Ludwika Waryńskiego') on conflict do nothing;
insert into street_names_mappings values('Waryńskiego', 'Ludwika Waryńskiego') on conflict do nothing;
insert into street_names_mappings values('Wasilewskiej', 'Wandy Wasilewskiej') on conflict do nothing;
insert into street_names_mappings values('Waszyngtona Jerzego', 'Jerzego Waszyngtona') on conflict do nothing;
insert into street_names_mappings values('Walasiewiczówny S.', 'Stanisławy Walasiewiczówny') on conflict do nothing;
insert into street_names_mappings values('Wańkowicza Melchiora', 'Melchiora Wańkowicza') on conflict do nothing;
insert into street_names_mappings values('Wieniawskiego Henryka', 'Henryka Wieniawskiego') on conflict do nothing;
insert into street_names_mappings values('"Wira" Bartoszewskiego', 'Konrada "Wira" Bartoszewskiego') on conflict do nothing;
insert into street_names_mappings values('Witosa', 'Wincentego Witosa') on conflict do nothing;
insert into street_names_mappings values('Witosa W.', 'Wincentego Witosa') on conflict do nothing;
insert into street_names_mappings values('Wołodyjowskiego Michała', 'Michała Wołodyjowskiego') on conflict do nothing;
insert into street_names_mappings values('Wojciecha św.', 'Świętego Wojciecha') on conflict do nothing;
insert into street_names_mappings values('Wróblewskiego Walerego', 'Walerego Wróblewskiego') on conflict do nothing;
insert into street_names_mappings values('Wybickiego J. gen.', 'Generała Józefa Wybickiego') on conflict do nothing;
insert into street_names_mappings values('Wybickiego Józefa', 'Józefa Wybickiego') on conflict do nothing;
insert into street_names_mappings values('Wybickiego', 'Józefa Wybickiego') on conflict do nothing;
insert into street_names_mappings values('Wyczółkowskiego Leona', 'Leona Wyczółkowskiego') on conflict do nothing;
insert into street_names_mappings values('Wyki Kazimierza', 'Kazimierza Wyki') on conflict do nothing;
insert into street_names_mappings values('Wyspiańskiego S.', 'Stanisława Wyspiańskiego') on conflict do nothing;
insert into street_names_mappings values('Wyspiańskiego Stanisława', 'Stanisława Wyspiańskiego') on conflict do nothing;
insert into street_names_mappings values('Wyspiańskiego', 'Stanisława Wyspiańskiego') on conflict do nothing;
insert into street_names_mappings values('Wyszyńskiego S. kard.', 'Kardynała Stefana Wyszyńskiego') on conflict do nothing;
insert into street_names_mappings values('Wyszyńskiego S.', 'Stefana Wyszyńskiego') on conflict do nothing;
insert into street_names_mappings values('Wyszyńskiego Stefana', 'Stefana Wyszyńskiego') on conflict do nothing;
insert into street_names_mappings values('Wyszyńskiego kard.', 'Kardynała Stefana Wyszyńskiego') on conflict do nothing;
insert into street_names_mappings values('Zamenhofa Ludwika', 'Ludwika Zamenhofa') on conflict do nothing;
insert into street_names_mappings values('Zana T.', 'Tomasza Zana') on conflict do nothing;
insert into street_names_mappings values('Zelenay A.', 'Anny Zelenay') on conflict do nothing;
insert into street_names_mappings values('Zapolskiej G.', 'Gabrieli Zapolskiej') on conflict do nothing;
insert into street_names_mappings values('Zapolskiej', 'Gabrieli Zapolskiej') on conflict do nothing;
insert into street_names_mappings values('Zaruskiego Mariusza', 'Mariusza Zaruskiego') on conflict do nothing;
insert into street_names_mappings values('Zubrzyckiego Franciszka', 'Franciszka Zubrzyckiego') on conflict do nothing;
insert into street_names_mappings values('Łopuskiego Edmunda', 'Edmunda Łopuskiego') on conflict do nothing;
insert into street_names_mappings values('Łukasiewicza I.', 'Ignacego Łukasiewicza') on conflict do nothing;
insert into street_names_mappings values('Łukasiewicza Ignacego', 'Ignacego Łukasiewicza') on conflict do nothing;
insert into street_names_mappings values('Łukasińskiego W.', 'Waleriana Łukasińskiego') on conflict do nothing;
insert into street_names_mappings values('Łęckiej', 'Izabeli Łęckiej') on conflict do nothing;
insert into street_names_mappings values('Ściegiennego Piotra', 'Piotra Ściegiennego') on conflict do nothing;
insert into street_names_mappings values('Śliwińskiego Józefa', 'Józefa Śliwińskiego') on conflict do nothing;
insert into street_names_mappings values('Śnieżka Adama', 'Adama Śnieżka') on conflict do nothing;
insert into street_names_mappings values('Św. Ducha', 'Świętego Ducha') on conflict do nothing;
insert into street_names_mappings values('Św. Huberta', 'Świętego Huberta') on conflict do nothing;
insert into street_names_mappings values('Św. Jana', 'Świętego Jana') on conflict do nothing;
insert into street_names_mappings values('Św. Rozalii', 'Świętej Rozalii') on conflict do nothing;
insert into street_names_mappings values('Św. Wojciecha', 'Świętego Wojciecha') on conflict do nothing;
insert into street_names_mappings values('Św. Piotra', 'Świętego Piotra') on conflict do nothing;
insert into street_names_mappings values('Świerczewskiego', 'Karola Świerczewskiego') on conflict do nothing;
insert into street_names_mappings values('Świerczewskiego K. gen.', 'Generała Karola Świerczewskiego') on conflict do nothing;
insert into street_names_mappings values('Świerczewskiego K.gen.', 'Generała Karola Świerczewskiego') on conflict do nothing;
insert into street_names_mappings values('Żebrowskiego Michała', 'Michała Żebrowskiego') on conflict do nothing;
insert into street_names_mappings values('Żeromskiego S.', 'Stefana Żeromskiego') on conflict do nothing;
insert into street_names_mappings values('Żeromskiego Stefana', 'Stefana Żeromskiego') on conflict do nothing;
insert into street_names_mappings values('Żeromskiego', 'Stefana Żeromskiego') on conflict do nothing;
insert into street_names_mappings values('Żymierskiego', 'Michała Roli-Żymierskiego') on conflict do nothing;
insert into street_names_mappings values('Żółkiewskiego Stanisława', 'Stanisława Żółkiewskiego') on conflict do nothing;

-- new mappings
insert into street_names_mappings values('ppłk. Konrada', 'Podpułkownika "Konrada"') on conflict do nothing;
insert into street_names_mappings values('ks. Piotra Skargi', 'Księdza Piotra Skargi') on conflict do nothing;
insert into street_names_mappings values('J. Piłsudskiego', 'Józefa Piłsudskiego') on conflict do nothing;
